export const lstFilters = [
  { name: 'all', label: 'Todos', icon: 'house' },
  { name: 'nearby', label: 'Proximos', icon: 'radar' },
  { name: 'free', label: 'Gratuito', icon: 'bi-piggy-bank' },
  { name: 'technology', label: 'Tecnologia', icon: 'bi-pc-display' },
  {
    name: 'networking',
    label: 'Profissionais e Networking',
    icon: 'bi-globe2',
  },
  {
    name: 'educational',
    label: 'Estudantes e Educação',
    icon: 'bi-mortarboard',
  },
  { name: 'festival', label: 'Festival', icon: 'bi-boombox' },
  { name: 'arts', label: 'Artes', icon: 'bi-easel' },
  { name: 'family', label: 'Família e Crianças', icon: 'family_restroom' },
];

export const lstEvents = [
  {
    id: 'event_01',
    name: 'Tech Summit',
    date: { from: '2024-03-01', to: '2024-03-03' },
    distance: 150,
    price: 200,
    keywords: ['conference', 'technology', 'networking'],
    desc: 'Explore as últimas tendências tecnológicas e conecte-se com profissionais da indústria no Tech Summit.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_02',
    name: 'Festival de Artes',
    date: { from: '2024-04-15', to: '2024-04-18' },
    distance: 300,
    price: 50,
    keywords: ['festival', 'arts', 'family'],
    desc: 'Um festival cultural repleto de arte, música e entretenimento para toda a família aproveitar.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_03',
    name: 'Workshop de Fotografia',
    date: { from: '2024-05-10', to: '2024-05-12' },
    distance: 50,
    price: 120,
    keywords: ['workshop', 'photography', 'educational'],
    desc: 'Aprenda as técnicas de fotografia mais recentes e aprimore suas habilidades neste workshop exclusivo.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_04',
    name: 'Conferência de Negócios',
    date: { from: '2024-06-20', to: '2024-06-22' },
    distance: 200,
    price: 300,
    keywords: ['conference', 'business', 'networking'],
    desc: 'Uma conferência imperdível para profissionais de negócios abordando estratégias e inovações empresariais.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_05',
    name: 'Feira Gastronômica',
    date: { from: '2024-07-05', to: '2024-07-08' },
    distance: 120,
    price: 80,
    keywords: ['festival', 'food', 'family'],
    desc: 'Explore uma variedade de deliciosas opções gastronômicas nesta feira culinária ao ar livre.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_06',
    name: 'Concerto ao Pôr do Sol',
    date: { from: '2024-08-12', to: '2024-08-14' },
    distance: 10,
    price: 180,
    keywords: ['festival', 'music', 'calm'],
    desc: 'Desfrute de uma noite relaxante com música ao vivo enquanto o sol se põe no horizonte.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_07',
    name: 'Feira de Inovação',
    date: { from: '2024-09-01', to: '2024-09-03' },
    distance: 180,
    price: 400,
    keywords: ['festival', 'innovation', 'educational'],
    desc: 'Descubra as últimas inovações e tecnologias em uma feira dedicada à criatividade e ao progresso.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_08',
    name: 'Caminhada Ecológica',
    date: { from: '2024-10-15', to: '2024-10-17' },
    distance: 5,
    price: 0,
    keywords: ['family', 'free', 'educational'],
    desc: 'Participe de uma caminhada ecológica gratuita e aprenda sobre a preservação da natureza.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_09',
    name: 'Sessões de Yoga ao Ar Livre',
    date: { from: '2024-11-08', to: '2024-11-10' },
    distance: 30,
    price: 70,
    keywords: ['workshop', 'health', 'calm'],
    desc: 'Pratique yoga ao ar livre e promova o equilíbrio entre corpo e mente.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_10',
    name: 'Feira de Livros',
    date: { from: '2024-12-05', to: '2024-12-07' },
    distance: 250,
    price: 30,
    keywords: ['festival', 'books', 'educational'],
    desc: 'Explore uma variedade de livros em uma feira dedicada à literatura e à aprendizagem.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_11',
    name: 'Exposição de Arte Local',
    date: { from: '2025-01-20', to: '2025-01-22' },
    distance: 100,
    price: 150,
    keywords: ['arts', 'local', 'family'],
    desc: 'Descubra obras de artistas locais em uma exposição de arte vibrante e diversificada.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_12',
    name: 'Semana da Moda',
    date: { from: '2025-02-15', to: '2025-02-17' },
    distance: 80,
    price: 250,
    keywords: ['festival', 'fashion', 'networking'],
    desc: 'Explore as últimas tendências da moda em desfiles e eventos exclusivos durante a Semana da Moda.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_13',
    name: 'Competição de Culinária',
    date: { from: '2025-03-10', to: '2025-03-12' },
    distance: 200,
    price: 120,
    keywords: ['festival', 'food', 'competition'],
    desc: 'Assista a chefs talentosos competindo em uma emocionante competição culinária.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_14',
    name: 'Feira de Ciências',
    date: { from: '2025-04-18', to: '2025-04-20' },
    distance: 150,
    price: 80,
    keywords: ['educational', 'science', 'family'],
    desc: 'Explore experimentos e descobertas científicas em uma emocionante feira de ciências.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
  {
    id: 'event_15',
    name: 'Concerto de Natal',
    date: { from: '2025-12-20', to: '2025-12-22' },
    distance: 120,
    price: 60,
    keywords: ['festival', 'music', 'family'],
    desc: 'Celebre a temporada festiva com um encantador concerto de músicas natalinas.',
    image:
      'https://thelawgivers.com/wp-content/uploads/2016/04/dummy-post-horisontal.jpg',
    participants: Math.floor(Math.random() * 150) + 1,
    capacity: Math.floor(Math.random() * 500) + 1,
  },
];
